# Pandas SQLite3

In [1]:
import pandas as pd
import numpy as np
import sqlite3

In [2]:
import matplotlib 
import matplotlib.pyplot as plt

In [3]:
columns = [ "rowid","empid","name","managerid","dateOfjoin","city"]

rowid = [0,1,2,3]
empid =  [121,221,321,421]
name  = ['nurur rahman', 'abdur rahman', 'britany spears', 'sam adams']
managerid = [321,986,876,986]
city      = ['Toronto', 'New York','Los Angeles', 'New York']
dateOfjoin= ['01/31/2014','02/30/2015','11/27/2016','12/30/2018']


values = [rowid,empid,name,managerid,dateOfjoin,city]

df1  =  pd.DataFrame({columns[i]: values[i] for i in range(6)}, columns=columns)
df1

rowid  empid            name  managerid  dateOfjoin         city
0      0    121    nurur rahman        321  01/31/2014      Toronto
1      1    221    abdur rahman        986  02/30/2015     New York
2      2    321  britany spears        876  11/27/2016  Los Angeles
3      3    421       sam adams        986  12/30/2018     New York

# 

In [4]:
columns  = [ "empid","project","grade","salary","variable"]

empid    = [121,221,321,571]
project  = ['p1','p2','p3','p2']
grade    = ['a','b','a','c']
salary   = [8000, 10000, 12000, 11300]
variable = [500, 800,0, 100]

values = [empid,project,grade,salary,variable]

df2  =  pd.DataFrame({columns[i]: values[i] for i in range(5)}, columns=columns)
df2

empid project grade  salary  variable
0    121      p1     a    8000       500
1    221      p2     b   10000       800
2    321      p3     a   12000         0
3    571      p2     c   11300       100

In [5]:
conn = sqlite3.connect( ':memory:' )

df1.to_sql('empDetails', conn)
df2.to_sql('empSalary', conn)

4

Write an SQL query to fetch the EmpID and FullName of all the employees working under ManagerID – '986'

In [6]:
myquery ="""
SELECT empid, name
FROM empDetails
WHERE managerid='986'
"""

pd.read_sql(myquery,conn)

empid          name
0    221  abdur rahman
1    421     sam adams

Write an SQL query to fetch the different projects available from the EmployeeSalary table

In [7]:
myquery ="""
SELECT project
FROM empSalary
"""

pd.read_sql(myquery,conn)

project
0      p1
1      p2
2      p3
3      p2

Write an SQL query to fetch the count of employees working in project 'P1'

In [8]:
myquery ="""
SELECT COUNT(*) count 
FROM
(SELECT 
f1.empid, 
f2.project
FROM empDetails as f1
JOIN
empSalary as f2
ON f1.empid = f2.empid
WHERE f2.project='p1') as f
"""

pd.read_sql(myquery,conn)

count
0      1

Write an SQL query to find the maximum, minimum, and average salary of the employees

In [9]:
myquery ="""
SELECT 
min(salary) as min_salary,
max(salary) as max_salary,
avg(salary) as mean_salary
FROM empSalary
"""

pd.read_sql(myquery,conn)

min_salary  max_salary  mean_salary
0        8000       12000      10325.0

Write an SQL query to find the employee id whose salary lies in the range of 9000 and 15000

In [10]:
myquery ="""
SELECT *
FROM empSalary
WHERE salary BETWEEN 9000 AND 15000
"""
pd.read_sql(myquery,conn)

index  empid project grade  salary  variable
0      1    221      p2     b   10000       800
1      2    321      p3     a   12000         0
2      3    571      p2     c   11300       100

Write an SQL query to fetch those employees who live in Toronto and work under manager with ManagerId 321

In [11]:
myquery ="""
SELECT *
FROM empDetails
WHERE city='Toronto'
AND managerid = 321
"""
pd.read_sql(myquery,conn)

index  rowid  empid          name  managerid  dateOfjoin     city
0      0      0    121  nurur rahman        321  01/31/2014  Toronto

Write an SQL query to fetch all the employees who either live in California or work under a manager with ManagerId 321

In [12]:
myquery ="""
SELECT *
FROM empDetails
WHERE city='New York'
OR managerid = 321
"""
pd.read_sql(myquery,conn)

index  rowid  empid          name  managerid  dateOfjoin      city
0      0      0    121  nurur rahman        321  01/31/2014   Toronto
1      1      1    221  abdur rahman        986  02/30/2015  New York
2      3      3    421     sam adams        986  12/30/2018  New York

Write an SQL query to fetch all those employees who work on Project other than P1

In [13]:
myquery ="""
SELECT 
f1.*, 
f2.*
FROM empDetails as f1
JOIN
empSalary as f2
ON f1.empid = f2.empid
WHERE f2.project <> 'p2'
"""

pd.read_sql(myquery,conn)

index  rowid  empid            name  managerid  dateOfjoin         city  \
0      0      0    121    nurur rahman        321  01/31/2014      Toronto   
1      2      2    321  britany spears        876  11/27/2016  Los Angeles   

   index  empid project grade  salary  variable  
0      0    121      p1     a    8000       500  
1      2    321      p3     a   12000         0

Write an SQL query to display the total salary of each employee adding the Salary with Variable value

In [14]:
myquery ="""
SELECT salary+variable as total_salary
FROM empSalary
"""
pd.read_sql(myquery,conn)

total_salary
0          8500
1         10800
2         12000
3         11400

Write an SQL query to fetch the employees whose name begins with any two characters, followed by a text “hn” and ending with any sequence of characters

In [15]:
myquery ="""
SELECT *
FROM empDetails
WHERE name LIKE 'nu%'
"""
pd.read_sql(myquery,conn)

index  rowid  empid          name  managerid  dateOfjoin     city
0      0      0    121  nurur rahman        321  01/31/2014  Toronto

In [16]:
myquery ="""
SELECT *
FROM empDetails
WHERE LENGTH(name)>12
"""
pd.read_sql(myquery,conn)

index  rowid  empid            name  managerid  dateOfjoin         city
0      2      2    321  britany spears        876  11/27/2016  Los Angeles

Write an SQL query to fetch all the EmpIds which are present in either of the tables – 'EmployeeDetails' and 'EmployeeSalary'

In [17]:
myquery ="""
SELECT 
f1.empid
FROM empDetails as f1
INNER JOIN
empSalary as f2
ON f1.empid = f2.empid
"""
pd.read_sql(myquery,conn)

empid
0    121
1    221
2    321

In [18]:
myquery ="""
SELECT empid FROM empDetails
UNION 
SELECT empid FROM empSalary
"""
pd.read_sql(myquery,conn)

empid
0    121
1    221
2    321
3    421
4    571

Write an SQL query to fetch common records between two tables

In [19]:
# myquery ="""
# SELECT * FROM empDetails
# INTERSECT
# SELECT * FROM empSalary
# """
# pd.read_sql(myquery,conn)

Write an SQL query to fetch records that are present in one table but not in another table

In [20]:
myquery ="""
SELECT 
f1.*, 
f2.*
FROM empDetails as f1
LEFT JOIN
empSalary as f2
ON f1.empid = f2.empid
WHERE f2.empid IS NULL
"""

pd.read_sql(myquery,conn)

index  rowid empid       name  managerid  dateOfjoin      city index empid  \
0     3      3   421  sam adams        986  12/30/2018  New York  None  None   

  project grade salary variable  
0    None  None   None     None

Write an SQL query to fetch the EmpIds that are present in both the tables –   'EmployeeDetails' and 'EmployeeSalary'

In [21]:
myquery ="""
SELECT empid FROM empDetails
WHERE empid IN
(SELECT empid FROM empSalary)
"""
pd.read_sql(myquery,conn)

empid
0    121
1    221
2    321

Write an SQL query to fetch the EmpIds that are present in EmployeeDetails but not in EmployeeSalary

In [22]:
myquery ="""
SELECT empid FROM empDetails
WHERE empid NOT IN
(SELECT empid FROM empSalary)
"""
pd.read_sql(myquery,conn)

empid
0    421

Write an SQL query to fetch the employee full names and replace the space with '-'

In [23]:
myquery ="""
SELECT 
REPLACE(name,' ', '-') 
FROM empDetails
"""
pd.read_sql(myquery,conn)

REPLACE(name,' ', '-')
0           nurur-rahman
1           abdur-rahman
2         britany-spears
3              sam-adams

Write an SQL query to concat both the EmpId and ManagerId together

In [24]:
myquery ="""
SELECT empid || '-' || managerid as emp_mng
FROM empDetails
"""
pd.read_sql(myquery,conn)

emp_mng
0  121-321
1  221-986
2  321-876
3  421-986

Write an SQL query to fetch the position of a given character(s) in a field

In [25]:
myquery ="""
SELECT 
INSTR(name,'adams') as IN_STRING
FROM empDetails
"""
pd.read_sql(myquery,conn)

IN_STRING
0          0
1          0
2          0
3          5

Write a query to fetch only the first name (string before space) from the name column of the EmployeeDetails table

In [26]:
myquery ="""
SELECT 
SUBSTR(name, 0, INSTR(name,' ')) as white_space
FROM empDetails
"""
pd.read_sql(myquery,conn)

white_space
0       nurur
1       abdur
2     britany
3         sam

Write an SQL query to upper case the name of the employee and lower case the city values

In [27]:
myquery ="""
SELECT 
UPPER(name) as name_upper_case,
LOWER(city) as city_lower_case
FROM empDetails
"""
pd.read_sql(myquery,conn)

name_upper_case city_lower_case
0    NURUR RAHMAN         toronto
1    ABDUR RAHMAN        new york
2  BRITANY SPEARS     los angeles
3       SAM ADAMS        new york

Write an SQL query to find the count of the total occurrences of a particular character – ‘n’ in the name field

In [28]:
myquery ="""
SELECT 
LENGTH(name) - LENGTH( REPLACE(name,'n','')) as number
FROM empDetails
"""
pd.read_sql(myquery,conn)

number
0       2
1       1
2       1
3       0

Write an SQL query to update the employee names by removing leading and trailing spaces

In [29]:
myquery ="""
SELECT 
TRIM( REPLACE(name,'n',' ') ) as new_name
FROM empDetails
"""
pd.read_sql(myquery,conn)

new_name
0      urur rahma
1     abdur rahma
2  brita y spears
3       sam adams

Fetch all the employees who are not working on any project

In [30]:
myquery ="""
SELECT 
f1.empid, f2.project
FROM empDetails as f1
JOIN empSalary as f2
ON f1.empid = f2.empid
WHERE f2.project IS NULL
"""
pd.read_sql(myquery,conn)

Empty DataFrame
Columns: [empid, project]
Index: []

Write an SQL query to fetch all the Employees details from EmployeeDetails table who joined in the Year 2020

In [31]:
myquery ="""
SELECT * 
FROM
(SELECT *,
DATE( SUBSTR(dateOfjoin,7,4) || '-' || SUBSTR(dateOfjoin,1,2) || '-' || SUBSTR(dateOfjoin,4,2)) as join_date
FROM empDetails) as f
WHERE strftime('%Y', join_date) = '2016'
"""
pd.read_sql(myquery,conn)

index  rowid  empid            name  managerid  dateOfjoin         city  \
0      2      2    321  britany spears        876  11/27/2016  Los Angeles   

    join_date  
0  2016-11-27

Write an SQL query to fetch all employee records from EmployeeDetails table who have a salary record in EmployeeSalary table

In [32]:
myquery ="""
SELECT * FROM empDetails f1
WHERE EXISTS
(SELECT * FROM empSalary f2 
WHERE  f1.empid = f2.empid)
"""
pd.read_sql(myquery,conn)

index  rowid  empid            name  managerid  dateOfjoin         city
0      0      0    121    nurur rahman        321  01/31/2014      Toronto
1      1      1    221    abdur rahman        986  02/30/2015     New York
2      2      2    321  britany spears        876  11/27/2016  Los Angeles

Write a query to fetch employee names and salary records.

In [33]:
myquery ="""
SELECT 
f1.name, f2.salary
FROM empDetails as f1
LEFT JOIN empSalary as f2
ON f1.empid = f2.empid
"""
pd.read_sql(myquery,conn)

name   salary
0    nurur rahman   8000.0
1    abdur rahman  10000.0
2  britany spears  12000.0
3       sam adams      NaN

Self  Join

Write an SQL query to fetch all the Employees who are also managers from the EmployeeDetails table

In [34]:
myquery = """
SELECT 
f1.name as empName, 
f2.name  as managerName
FROM empDetails as f1
JOIN empDetails as f2
ON f1.managerid = f2.empid
"""
pd.read_sql(myquery,conn)

empName     managerName
0  nurur rahman  britany spears

Duplicate

Write an SQL query to fetch duplicate records from EmployeeDetails

In [35]:
myquery ="""
SELECT 
COUNT(*) as count,
name
FROM empDetails
GROUP BY name
HAVING count > 1
"""
pd.read_sql(myquery,conn)

Empty DataFrame
Columns: [count, name]
Index: []

Write an SQL query to fetch only odd rows from the table

In [36]:
myquery ="""
SELECT * 
FROM empDetails 
WHERE MOD(rowid,2) <> 0
"""
pd.read_sql(myquery,conn)

index  rowid  empid          name  managerid  dateOfjoin      city
0      1      1    221  abdur rahman        986  02/30/2015  New York
1      3      3    421     sam adams        986  12/30/2018  New York

In [37]:
myquery ="""
SELECT *
FROM
(SELECT *,
ROW_NUMBER() OVER() as rownum
FROM empDetails) as f
WHERE MOD(rownum,2) <> 0
"""
pd.read_sql(myquery,conn)

index  rowid  empid            name  managerid  dateOfjoin         city  \
0      0      0    121    nurur rahman        321  01/31/2014      Toronto   
1      2      2    321  britany spears        876  11/27/2016  Los Angeles   

   rownum  
0       1  
1       3

Top N

Write an SQL query to fetch top 2 records

In [38]:
myquery ="""
SELECT *
FROM
empSalary
ORDER BY salary DESC
LIMIT 2
"""
pd.read_sql(myquery,conn)

index  empid project grade  salary  variable
0      2    321      p3     a   12000         0
1      3    571      p2     c   11300       100

Nth Largest 

Write SQL query to find the 3rd highest salary from a table without using the TOP/LIMIT keyword

In [39]:
myquery ="""
SELECT * 
FROM
empSalary
WHERE salary =
(SELECT DISTINCT salary
FROM
empSalary
ORDER BY salary DESC
LIMIT 1 OFFSET 2)
"""
pd.read_sql(myquery,conn)

index  empid project grade  salary  variable
0      1    221      p2     b   10000       800

LIMIT M OFFSET N

In [40]:
myquery ="""
SELECT DISTINCT salary
FROM
empSalary
ORDER BY salary DESC
LIMIT 1 OFFSET 2
"""
pd.read_sql(myquery,conn)

salary
0   10000

## Date & Time

In [41]:
myquery ="""
SELECT REPLACE('10/18/1970','/','-') as date
"""
pd.read_sql(myquery,conn)

date
0  10-18-1970

Write an SQL query to convert string to date

In [42]:
myquery ="""
SELECT DATE( REPLACE('10/18/1970','/','-') ) as date
"""
pd.read_sql(myquery,conn)

date
0  None

In [43]:
myquery ="""
SELECT 
SUBSTR('10/18/1970',7,4) || '-' || SUBSTR('10/18/1970',1,2) || '-' || SUBSTR('10/18/1970',4,2) as str_date
"""
pd.read_sql(myquery,conn)

str_date
0  1970-10-18

In [44]:
myquery ="""
SELECT 
DATE( SUBSTR('10/18/1970',7,4) || '-' || SUBSTR('10/18/1970',1,2) || '-' || SUBSTR('10/18/1970',4,2)) as date
"""
pd.read_sql(myquery,conn)

date
0  1970-10-18

In [45]:
myquery ="""
SELECT DATE('1970-10-18') as date
"""
pd.read_sql(myquery,conn)

date
0  1970-10-18

Write an SQL query to get year  from date

In [46]:
myquery ="""
SELECT 
strftime('%Y', DATE('1970-10-18') ) as date,
strftime('%m', DATE('1970-10-18') ) as month
"""
pd.read_sql(myquery,conn)

date month
0  1970    10

Write an SQL query to find date

In [47]:
myquery ="""
SELECT 
DATE('now') as now,
DATE() as date,
DATETIME() as datetime
"""
pd.read_sql(myquery,conn)

now        date             datetime
0  2022-09-25  2022-09-25  2022-09-25 23:49:47

Date & Date Differences

In [48]:
myquery ="""
SELECT 
DATE('1970-10-18') as date1, 
DATE()-DATE('1970-10-18') as date2, 
(julianday() - julianday( DATE('1970-10-18')) )/365.0 as date3
"""
pd.read_sql(myquery,conn)

date1  date2      date3
0  1970-10-18     52  51.975323

In [49]:
conn.close()